name: GarlandThompson
favicon: null
layout_spectrum: 0.37800080538727343
typography_spectrum: 0.3509651601780206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#1b1b1d'
    - '#a99eaf'
    - '#fd0000'
    - '#1bcdfd'
  brandStrength: 0.7712283732835203
  lightness: 0.5
  saturation: 0.036857986357063055
  rhythmicContrast: 0.75
purpose: []
